baseURL = 'https://xiecy02.github.io/'
languageCode = 'zh-cn'
title = 'Sakura Diaries'
theme = 'PaperMod'

[params]
    env = "production"
    customCSS = ["css/extended.css"]
    [params.profileMode]
        enabled = true
        title = "Sakura Diaries"
        subtitle = "Study | Life"

[markup.goldmark.renderer]
    unsafe = true